# Generated by Django 5.0.7 on 2024-08-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maximaapp', '0002_product_delete_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pimage',
            field=models.ImageField(default=0, upload_to='image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='cat',
            field=models.IntegerField(choices=[(1, 'casio'), (2, 'fastrack'), (3, 'rolex'), (4, 'titan')], verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='available'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50, verbose_name='product name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pdetails',
            field=models.CharField(max_length=100, verbose_name='product details'),
        ),
    ]
